### ISSUE TITLE
at atom 1.12.0 on linux

### ISSUE THREAD

**Issue by peter-holm** [t-ishii/backupper#9]
Below is the stacktrace. As I assume it is because somethinfg have changed in atom editor after the last update (which is the fact with the note addon) I will  test with atom 1.10.2 int same machine, same config. 

#################################################
Uncaught TypeError: "encoding" must be a valid string encoding
buffer.js:186
Hide Stack Trace
TypeError: "encoding" must be a valid string encoding
    at fromString (buffer.js:186:11)
    at Function.Buffer.from (buffer.js:94:12)
    at decodeChunk (_stream_writable.js:261:20)
    at writeOrBuffer (_stream_writable.js:270:11)
    at WriteStream.Writable.write (_stream_writable.js:220:11)
    at Action.module.exports.Action.writeFile (/home/peter/.atom/packages/backupper/lib/backupper-action.coffee:57:8)
    at Action.module.exports.Action.save (/home/peter/.atom/packages/backupper/lib/backupper-action.coffee:70:6)
    at Array.<anonymous> (/home/peter/.atom/packages/backupper/lib/backupper.coffee:25:29)
    at toggleState (/home/peter/.atom/packages/backupper/node_modules/away/index.js:144:15)
    at Idle.self.state.state_fn (/home/peter/.atom/packages/backupper/node_modules/away/index.js:37:9)

**Comment by patricocoblenzo** [comment]
Same here Atom 1.15.0 Mac el Capitan.
